# Generated by Django 3.1.1 on 2020-09-21 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=225)),
                ('Email', models.EmailField(max_length=225, unique=True)),
                ('Password', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=225)),
                ('QtyInStock', models.IntegerField(default=0)),
                ('BuyPrice', models.IntegerField()),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('AddedDate', models.DateTimeField(default=datetime.datetime(2020, 9, 21, 11, 58, 57, 429686, tzinfo=utc))),
                ('LastEdit', models.DateTimeField(default=datetime.datetime(2020, 9, 21, 11, 58, 57, 429705, tzinfo=utc))),
            ],
        ),
    ]
