# Generated by Django 3.1.1 on 2020-09-22 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='AddedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 6, 42, 33, 594383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='LastEdit',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 6, 42, 33, 594403, tzinfo=utc)),
        ),
    ]
