# Generated by Django 3.1.1 on 2020-09-23 07:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200922_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='AddedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 7, 47, 17, 884563, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='LastEdit',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 7, 47, 17, 884584, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
