# Generated by Django 3.1.1 on 2020-09-24 17:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200923_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_item',
            old_name='ProductID',
            new_name='ProductCode',
        ),
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='AddedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 17, 0, 4, 686204, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='LastEdit',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 17, 0, 4, 686223, tzinfo=utc)),
        ),
    ]
