# Generated by Django 3.1.1 on 2020-09-24 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200924_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='AddedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 21, 29, 49, 437687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='LastEdit',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 21, 29, 49, 437707, tzinfo=utc)),
        ),
    ]
