# Generated by Django 3.1.1 on 2020-09-25 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200924_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='AddedDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='LastEdit',
        ),
        migrations.AddField(
            model_name='product',
            name='LastEdited',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 9, 26, 10, 152850, tzinfo=utc)),
        ),
    ]
